import React from 'react';
import { useActiveSignage } from '../hooks/useIncidents';
import { VirtualVMSSign } from '../components/VirtualVMSSign';
import { Tv, AlertTriangle, Radio, ShieldCheck } from 'lucide-react';

export const SignagePage: React.FC = () => {
  const { data: signs = [], isLoading } = useActiveSignage();

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 space-y-8">
      {/* Header */}
      <div className="text-center space-y-2">
        <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-amber-950/80 border border-amber-800 text-amber-400 text-xs font-mono">
          <Tv className="w-3.5 h-3.5" />
          <span>MUNICIPAL ROADSIDE VMS SIMULATION NETWORK</span>
        </div>
        <h1 className="text-3xl font-extrabold text-white">
          Smart Roadside LED Variable Message Signs (VMS)
        </h1>
        <p className="text-sm text-slate-400 max-w-xl mx-auto">
          Pixel-accurate simulation of highway electronic variable message signs
          broadcasting real-time detour advisories generated by Gemini 2.5 Flash.
        </p>
      </div>

      {isLoading ? (
        <div className="p-16 text-center text-slate-500 font-mono text-sm animate-pulse">
          Connecting to roadside signage telematics...
        </div>
      ) : signs.length === 0 ? (
        <div className="p-12 text-center bg-command-900 border border-command-800 rounded-3xl space-y-3">
          <ShieldCheck className="w-8 h-8 text-emerald-400 mx-auto" />
          <h3 className="font-bold text-lg text-white">
            All Municipal Corridors Clear
          </h3>
          <p className="text-xs text-slate-400 max-w-md mx-auto">
            No active critical road closures or hazard detours at this time.
            Signage boards are displaying standard civic speed advisories.
          </p>
          <div className="pt-4">
            <VirtualVMSSign
              terminalName="METRO CIVIC GANTRY #101"
              line1="ALL ROADWAYS OPEN - DRIVE WITH CARE"
              line2="BUCKLE UP - OBEY SPEED LIMITS"
              isUrgent={false}
              speedLimitMph={35}
            />
          </div>
        </div>
      ) : (
        <div className="space-y-8">
          {signs.map((sign) => (
            <div key={sign.sign_id} className="space-y-2">
              <VirtualVMSSign
                terminalName={sign.terminal_name}
                line1={sign.vms_display_line_1}
                line2={sign.vms_display_line_2}
                isUrgent={sign.flashing_amber_alert}
                speedLimitMph={sign.recommended_speed_mph}
                detourText={sign.detour_instructions}
              />
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
